<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
  </head>
  <body>
    <script>
      function fetchData() {
        return new Promise((resolve, reject) => {
          // 请求会在 1 秒后失败
          setTimeout(() => {
            reject("err");
          }, 1000);
        });
      }

      // load 函数接收一个 onError 回调函数
      function load(onError) {
        // 请求接口，得到 Promise 实例
        const p = fetchData();

        // 捕获错误
        return p.catch((err) => {
          // 当错误发生时，返回一个新的 Promise 实例，并调用 onError 回调，
          // 同时将 retry 函数作为 onError 回调的参数
          return new Promise((resolve, reject) => {
            // retry 函数，用来执行重试的函数，执行该函数会重新调用 load 函数并发送请求
            const retry = () => resolve(load(onError));
            const fail = () => reject(err);
            onError(retry, fail);
          });
        });
      }

      // 调用 load 函数加载资源
      load(
        // onError 回调
        (retry, fail) => {
          // 失败后重试
          retry();
        }
      )
        .then((res) => {
          // 成功
          console.log(res);
        })
        .catch((err) => {
          // 处理最终的错误
          console.error(err);
        });
    </script>
  </body>
</html>
